package poly

var LockManager = map[string]string{
	"eth": `[{
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "fromAssetHash",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint64",
		"name": "toChainId",
		"type": "uint64"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "targetProxyHash",
		"type": "bytes"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "initialAmount",
		"type": "uint256"
	}],
	"name": "BindAssetEvent",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "uint64",
		"name": "toChainId",
		"type": "uint64"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "targetProxyHash",
		"type": "bytes"
	}],
	"name": "BindProxyEvent",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "fromAssetHash",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "address",
		"name": "fromAddress",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint64",
		"name": "toChainId",
		"type": "uint64"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "toAssetHash",
		"type": "bytes"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "toAddress",
		"type": "bytes"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "amount",
		"type": "uint256"
	}],
	"name": "LockEvent",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "previousOwner",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "newOwner",
		"type": "address"
	}],
	"name": "OwnershipTransferred",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "manager",
		"type": "address"
	}],
	"name": "SetManagerProxyEvent",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "toAssetHash",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "address",
		"name": "toAddress",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "amount",
		"type": "uint256"
	}],
	"name": "UnlockEvent",
	"type": "event"
}, {
	"constant": true,
	"inputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}, {
		"internalType": "uint64",
		"name": "",
		"type": "uint64"
	}],
	"name": "assetHashMap",
	"outputs": [{
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
		"internalType": "address",
		"name": "fromAssetHash",
		"type": "address"
	}, {
		"internalType": "uint64",
		"name": "toChainId",
		"type": "uint64"
	}, {
		"internalType": "bytes",
		"name": "toAssetHash",
		"type": "bytes"
	}],
	"name": "bindAssetHash",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
		"internalType": "uint64",
		"name": "toChainId",
		"type": "uint64"
	}, {
		"internalType": "bytes",
		"name": "targetProxyHash",
		"type": "bytes"
	}],
	"name": "bindProxyHash",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": true,
	"inputs": [{
		"internalType": "address",
		"name": "fromAssetHash",
		"type": "address"
	}],
	"name": "getBalanceFor",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": true,
	"inputs": [],
	"name": "isOwner",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
		"internalType": "address",
		"name": "fromAssetHash",
		"type": "address"
	}, {
		"internalType": "uint64",
		"name": "toChainId",
		"type": "uint64"
	}, {
		"internalType": "bytes",
		"name": "toAddress",
		"type": "bytes"
	}, {
		"internalType": "uint256",
		"name": "amount",
		"type": "uint256"
	}],
	"name": "lock",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"payable": true,
	"stateMutability": "payable",
	"type": "function"
}, {
	"constant": true,
	"inputs": [],
	"name": "managerProxyContract",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": true,
	"inputs": [],
	"name": "owner",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": true,
	"inputs": [{
		"internalType": "uint64",
		"name": "",
		"type": "uint64"
	}],
	"name": "proxyHashMap",
	"outputs": [{
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": false,
	"inputs": [],
	"name": "renounceOwnership",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
		"internalType": "address",
		"name": "ethCCMProxyAddr",
		"type": "address"
	}],
	"name": "setManagerProxy",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
		"internalType": "address",
		"name": "newOwner",
		"type": "address"
	}],
	"name": "transferOwnership",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
		"internalType": "bytes",
		"name": "argsBs",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "fromContractAddr",
		"type": "bytes"
	}, {
		"internalType": "uint64",
		"name": "fromChainId",
		"type": "uint64"
	}],
	"name": "unlock",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}]`,
}

var EthCrossChainManager = map[string]string{
	"bsc": `[{
	"inputs": [{
	"internalType": "address",
	"name": "_eccd",
	"type": "address"
}, {
	"internalType": "uint64",
	"name": "_chainId",
	"type": "uint64"
}, {
	"internalType": "address[]",
	"name": "fromContractWhiteList",
	"type": "address[]"
}, {
	"internalType": "bytes[]",
	"name": "contractMethodWhiteList",
	"type": "bytes[]"
}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "constructor"
}, {
	"anonymous": false,
	"inputs": [{
	"indexed": false,
	"internalType": "uint256",
	"name": "height",
	"type": "uint256"
}, {
	"indexed": false,
	"internalType": "bytes",
	"name": "rawHeader",
	"type": "bytes"
}],
	"name": "ChangeBookKeeperEvent",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
	"indexed": true,
	"internalType": "address",
	"name": "sender",
	"type": "address"
}, {
	"indexed": false,
	"internalType": "bytes",
	"name": "txId",
	"type": "bytes"
}, {
	"indexed": false,
	"internalType": "address",
	"name": "proxyOrAssetContract",
	"type": "address"
}, {
	"indexed": false,
	"internalType": "uint64",
	"name": "toChainId",
	"type": "uint64"
}, {
	"indexed": false,
	"internalType": "bytes",
	"name": "toContract",
	"type": "bytes"
}, {
	"indexed": false,
	"internalType": "bytes",
	"name": "rawdata",
	"type": "bytes"
}],
	"name": "CrossChainEvent",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
	"indexed": false,
	"internalType": "uint256",
	"name": "height",
	"type": "uint256"
}, {
	"indexed": false,
	"internalType": "bytes",
	"name": "rawHeader",
	"type": "bytes"
}],
	"name": "InitGenesisBlockEvent",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
	"indexed": true,
	"internalType": "address",
	"name": "previousOwner",
	"type": "address"
}, {
	"indexed": true,
	"internalType": "address",
	"name": "newOwner",
	"type": "address"
}],
	"name": "OwnershipTransferred",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
	"indexed": false,
	"internalType": "address",
	"name": "account",
	"type": "address"
}],
	"name": "Paused",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
	"indexed": false,
	"internalType": "address",
	"name": "account",
	"type": "address"
}],
	"name": "Unpaused",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
	"indexed": false,
	"internalType": "uint64",
	"name": "fromChainID",
	"type": "uint64"
}, {
	"indexed": false,
	"internalType": "bytes",
	"name": "toContract",
	"type": "bytes"
}, {
	"indexed": false,
	"internalType": "bytes",
	"name": "crossChainTxHash",
	"type": "bytes"
}, {
	"indexed": false,
	"internalType": "bytes",
	"name": "fromChainTxHash",
	"type": "bytes"
}],
	"name": "VerifyHeaderAndExecuteTxEvent",
	"type": "event"
}, {
	"constant": true,
	"inputs": [],
	"name": "EthCrossChainDataAddress",
	"outputs": [{
	"internalType": "address",
	"name": "",
	"type": "address"
}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": true,
	"inputs": [],
	"name": "chainId",
	"outputs": [{
	"internalType": "uint64",
	"name": "",
	"type": "uint64"
}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "bytes",
	"name": "rawHeader",
	"type": "bytes"
}, {
	"internalType": "bytes",
	"name": "pubKeyList",
	"type": "bytes"
}, {
	"internalType": "bytes",
	"name": "sigList",
	"type": "bytes"
}],
	"name": "changeBookKeeper",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "uint64",
	"name": "toChainId",
	"type": "uint64"
}, {
	"internalType": "bytes",
	"name": "toContract",
	"type": "bytes"
}, {
	"internalType": "bytes",
	"name": "method",
	"type": "bytes"
}, {
	"internalType": "bytes",
	"name": "txData",
	"type": "bytes"
}],
	"name": "crossChain",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "bytes",
	"name": "rawHeader",
	"type": "bytes"
}, {
	"internalType": "bytes",
	"name": "pubKeyList",
	"type": "bytes"
}],
	"name": "initGenesisBlock",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": true,
	"inputs": [],
	"name": "isOwner",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": true,
	"inputs": [],
	"name": "owner",
	"outputs": [{
	"internalType": "address",
	"name": "",
	"type": "address"
}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": false,
	"inputs": [],
	"name": "pause",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": true,
	"inputs": [],
	"name": "paused",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "bytes[]",
	"name": "contractMethodWhiteList",
	"type": "bytes[]"
}],
	"name": "removeContractMethodWhiteList",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "address[]",
	"name": "fromContractWhiteList",
	"type": "address[]"
}],
	"name": "removeFromContractWhiteList",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [],
	"name": "renounceOwnership",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "uint64",
	"name": "_newChainId",
	"type": "uint64"
}],
	"name": "setChainId",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "bytes[]",
	"name": "contractMethodWhiteList",
	"type": "bytes[]"
}],
	"name": "setContractMethodWhiteList",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "address[]",
	"name": "fromContractWhiteList",
	"type": "address[]"
}],
	"name": "setFromContractWhiteList",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "address",
	"name": "newWL",
	"type": "address"
}],
	"name": "setWhiteLister",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "address",
	"name": "newOwner",
	"type": "address"
}],
	"name": "transferOwnership",
	"outputs": [],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [],
	"name": "unpause",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "address",
	"name": "newEthCrossChainManagerAddress",
	"type": "address"
}],
	"name": "upgradeToNew",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": false,
	"inputs": [{
	"internalType": "bytes",
	"name": "proof",
	"type": "bytes"
}, {
	"internalType": "bytes",
	"name": "rawHeader",
	"type": "bytes"
}, {
	"internalType": "bytes",
	"name": "headerProof",
	"type": "bytes"
}, {
	"internalType": "bytes",
	"name": "curRawHeader",
	"type": "bytes"
}, {
	"internalType": "bytes",
	"name": "headerSig",
	"type": "bytes"
}],
	"name": "verifyHeaderAndExecuteTx",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": true,
	"inputs": [{
	"internalType": "address",
	"name": "",
	"type": "address"
}, {
	"internalType": "bytes",
	"name": "",
	"type": "bytes"
}],
	"name": "whiteListContractMethodMap",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": true,
	"inputs": [{
	"internalType": "address",
	"name": "",
	"type": "address"
}],
	"name": "whiteListFromContract",
	"outputs": [{
	"internalType": "bool",
	"name": "",
	"type": "bool"
}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": true,
	"inputs": [],
	"name": "whiteLister",
	"outputs": [{
	"internalType": "address",
	"name": "",
	"type": "address"
}],
	"payable": false,
	"stateMutability": "view",
	"type": "function"
}]`}

var switcheo = map[string]string{
	"arbitrum": `[{
	"inputs": [{
		"internalType": "address",
		"name": "_ccmProxyAddress",
		"type": "address"
	}, {
		"internalType": "uint64",
		"name": "_counterpartChainId",
		"type": "uint64"
	}],
	"stateMutability": "nonpayable",
	"type": "constructor"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "tokenAddress",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "fromAddress",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "uint64",
		"name": "toChainId",
		"type": "uint64"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "toAssetHash",
		"type": "bytes"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "toAddress",
		"type": "bytes"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "txArgs",
		"type": "bytes"
	}],
	"name": "LockEvent",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": true,
		"internalType": "address",
		"name": "tokenAddress",
		"type": "address"
	}, {
		"indexed": true,
		"internalType": "address",
		"name": "toAddress",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "amount",
		"type": "uint256"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "txArgs",
		"type": "bytes"
	}],
	"name": "UnlockEvent",
	"type": "event"
}, {
	"inputs": [],
	"name": "ETH_ADDRESS",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "SALT_PREFIX",
	"outputs": [{
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes",
		"name": "_argsBz",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}, {
		"internalType": "uint64",
		"name": "_fromChainId",
		"type": "uint64"
	}],
	"name": "addExtension",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [],
	"name": "ccmProxy",
	"outputs": [{
		"internalType": "contract CCMProxy",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "counterpartChainId",
	"outputs": [{
		"internalType": "uint64",
		"name": "",
		"type": "uint64"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "_ownerAddress",
		"type": "address"
	}, {
		"internalType": "bytes",
		"name": "_swthAddress",
		"type": "bytes"
	}],
	"name": "createWallet",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [],
	"name": "currentNonce",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "_receivingAddress",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "_tokenAddress",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "_amount",
		"type": "uint256"
	}],
	"name": "extensionTransfer",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"name": "extensions",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "_ownerAddress",
		"type": "address"
	}, {
		"internalType": "bytes",
		"name": "_swthAddress",
		"type": "bytes"
	}, {
		"internalType": "bytes32",
		"name": "_bytecodeHash",
		"type": "bytes32"
	}],
	"name": "getWalletAddress",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "_tokenAddress",
		"type": "address"
	}, {
		"internalType": "bytes",
		"name": "_targetProxyHash",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_toAddress",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_toAssetHash",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_feeAddress",
		"type": "bytes"
	}, {
		"internalType": "uint256[]",
		"name": "_values",
		"type": "uint256[]"
	}],
	"name": "lock",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "payable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address payable",
		"name": "_walletAddress",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "_tokenAddress",
		"type": "address"
	}, {
		"internalType": "bytes",
		"name": "_targetProxyHash",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_toAssetHash",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_feeAddress",
		"type": "bytes"
	}, {
		"internalType": "uint256[]",
		"name": "_values",
		"type": "uint256[]"
	}, {
		"internalType": "uint8",
		"name": "_v",
		"type": "uint8"
	}, {
		"internalType": "bytes32[]",
		"name": "_rs",
		"type": "bytes32[]"
	}],
	"name": "lockFromWallet",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes",
		"name": "_argsBz",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_fromContractAddr",
		"type": "bytes"
	}, {
		"internalType": "uint64",
		"name": "_fromChainId",
		"type": "uint64"
	}],
	"name": "registerAsset",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"name": "registry",
	"outputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes",
		"name": "_argsBz",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}, {
		"internalType": "uint64",
		"name": "_fromChainId",
		"type": "uint64"
	}],
	"name": "removeExtension",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"name": "seenMessages",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}, {
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}],
	"name": "tokenFallback",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes",
		"name": "_argsBz",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_fromContractAddr",
		"type": "bytes"
	}, {
		"internalType": "uint64",
		"name": "_fromChainId",
		"type": "uint64"
	}],
	"name": "unlock",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"name": "wallets",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"stateMutability": "payable",
	"type": "receive"
}]`,
	"eth": `[{
	"inputs": [{
		"internalType": "address",
		"name": "_ccmProxyAddress",
		"type": "address"
	}, {
		"internalType": "uint64",
		"name": "_counterpartChainId",
		"type": "uint64"
	}],
	"stateMutability": "nonpayable",
	"type": "constructor"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "fromAssetHash",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "address",
		"name": "fromAddress",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint64",
		"name": "toChainId",
		"type": "uint64"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "toAssetHash",
		"type": "bytes"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "toAddress",
		"type": "bytes"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "txArgs",
		"type": "bytes"
	}],
	"name": "LockEvent",
	"type": "event"
}, {
	"anonymous": false,
	"inputs": [{
		"indexed": false,
		"internalType": "address",
		"name": "toAssetHash",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "address",
		"name": "toAddress",
		"type": "address"
	}, {
		"indexed": false,
		"internalType": "uint256",
		"name": "amount",
		"type": "uint256"
	}, {
		"indexed": false,
		"internalType": "bytes",
		"name": "txArgs",
		"type": "bytes"
	}],
	"name": "UnlockEvent",
	"type": "event"
}, {
	"inputs": [],
	"name": "ETH_ASSET_HASH",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "SALT_PREFIX",
	"outputs": [{
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes",
		"name": "_argsBz",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}, {
		"internalType": "uint64",
		"name": "_fromChainId",
		"type": "uint64"
	}],
	"name": "addExtension",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [],
	"name": "ccmProxy",
	"outputs": [{
		"internalType": "contract CCMProxy",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [],
	"name": "counterpartChainId",
	"outputs": [{
		"internalType": "uint64",
		"name": "",
		"type": "uint64"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "_ownerAddress",
		"type": "address"
	}, {
		"internalType": "bytes",
		"name": "_swthAddress",
		"type": "bytes"
	}],
	"name": "createWallet",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [],
	"name": "currentNonce",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "_receivingAddress",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "_assetHash",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "_amount",
		"type": "uint256"
	}],
	"name": "extensionTransfer",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"name": "extensions",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "_ownerAddress",
		"type": "address"
	}, {
		"internalType": "bytes",
		"name": "_swthAddress",
		"type": "bytes"
	}, {
		"internalType": "bytes32",
		"name": "_bytecodeHash",
		"type": "bytes32"
	}],
	"name": "getWalletAddress",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "_assetHash",
		"type": "address"
	}, {
		"internalType": "bytes",
		"name": "_targetProxyHash",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_toAddress",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_toAssetHash",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_feeAddress",
		"type": "bytes"
	}, {
		"internalType": "uint256[]",
		"name": "_values",
		"type": "uint256[]"
	}],
	"name": "lock",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "payable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address payable",
		"name": "_walletAddress",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "_assetHash",
		"type": "address"
	}, {
		"internalType": "bytes",
		"name": "_targetProxyHash",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_toAssetHash",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_feeAddress",
		"type": "bytes"
	}, {
		"internalType": "uint256[]",
		"name": "_values",
		"type": "uint256[]"
	}, {
		"internalType": "uint8",
		"name": "_v",
		"type": "uint8"
	}, {
		"internalType": "bytes32[]",
		"name": "_rs",
		"type": "bytes32[]"
	}],
	"name": "lockFromWallet",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes",
		"name": "_argsBz",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_fromContractAddr",
		"type": "bytes"
	}, {
		"internalType": "uint64",
		"name": "_fromChainId",
		"type": "uint64"
	}],
	"name": "registerAsset",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"name": "registry",
	"outputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes",
		"name": "_argsBz",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}, {
		"internalType": "uint64",
		"name": "_fromChainId",
		"type": "uint64"
	}],
	"name": "removeExtension",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes32",
		"name": "",
		"type": "bytes32"
	}],
	"name": "seenMessages",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}, {
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}, {
		"internalType": "bytes",
		"name": "",
		"type": "bytes"
	}],
	"name": "tokenFallback",
	"outputs": [],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "bytes",
		"name": "_argsBz",
		"type": "bytes"
	}, {
		"internalType": "bytes",
		"name": "_fromContractAddr",
		"type": "bytes"
	}, {
		"internalType": "uint64",
		"name": "_fromChainId",
		"type": "uint64"
	}],
	"name": "unlock",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"inputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"name": "wallets",
	"outputs": [{
		"internalType": "bool",
		"name": "",
		"type": "bool"
	}],
	"stateMutability": "view",
	"type": "function"
}, {
	"stateMutability": "payable",
	"type": "receive"
}]`,
}
